# Generated by Django 4.1.1 on 2026-02-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='用户ID')),
                ('p_size', models.CharField(blank=True, help_text='用户选择尺寸，例如 160', max_length=50)),
                ('p_finish', models.CharField(blank=True, help_text='用户选择板面工艺，例如 glossy', max_length=50)),
                ('p_flex', models.CharField(blank=True, help_text='用户选择软硬度，例如 soft', max_length=50)),
                ('p_textures', models.JSONField(blank=True, default=list, help_text='用户选择纹理，可能多个，存 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customisations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='user ID')),
                ('order_number', models.CharField(editable=False, help_text='12-digit unique order number', max_length=12, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', help_text='order status: Pending/Confirmed/Shipped/Completed', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='total price in pounds, e.g. 199.99', max_digits=10)),
                ('address', models.TextField(blank=True, help_text='shipping address')),
                ('email', models.EmailField(blank=True, help_text='contact email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, '单品'), (2, '套装')], default=1)),
                ('status', models.BooleanField(default=True, help_text='是否上架')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='product price in pound, e.g. 199.99', max_digits=10)),
                ('p_desc', models.TextField(blank=True, help_text='产品描述')),
                ('p_size', models.CharField(default='0', help_text='例如 140,160,180；无尺寸用 0', max_length=100)),
                ('p_finish', models.CharField(blank=True, help_text='板面工艺，例如 matte / glossy', max_length=50)),
                ('p_flex', models.CharField(blank=True, help_text='软硬度，例如 soft / regular / stiff', max_length=50)),
                ('p_textures', models.JSONField(blank=True, default=dict, help_text='产品纹理JSON')),
                ('is_double_sided', models.BooleanField(default=False, help_text='是否双面纹理：False 表示单面，True 表示正反使用同一张图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50, unique=True)),
                ('texture_urls', models.JSONField(default=dict, help_text='例如 {"SB-001": ["front.png", "back.png"]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_assets',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='unit price in pounds, e.g. 199.99', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, help_text='related customisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.customisation')),
                ('order', models.ForeignKey(help_text='related order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(blank=True, help_text='related product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='customisation',
            name='product',
            field=models.ForeignKey(help_text='用户定制的产品', on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='api.product'),
        ),
        migrations.CreateModel(
            name='ProductAssetLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='api.productasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='api.product')),
            ],
            options={
                'db_table': 'product_asset_links',
                'unique_together': {('product', 'asset')},
            },
        ),
    ]
