# Generated by Django 5.2.10 on 2026-02-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, '单品'), (2, '套装')], default=1)),
                ('status', models.BooleanField(default=True, help_text='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=50, unique=True)),
                ('type_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('size', models.CharField(default='0', help_text='例如 140,160,180；无尺寸用 0', max_length=100)),
                ('topsheet_finish', models.CharField(blank=True, help_text='板面工艺，例如 matte / gloss', max_length=50)),
                ('flex', models.CharField(blank=True, help_text='软硬度，例如 soft / regular / stiff', max_length=50)),
                ('texture_urls', models.JSONField(default=dict, help_text='例如 {"SB-001": ["front.png", "back.png"]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_assets',
            },
        ),
        migrations.CreateModel(
            name='ProductAssetLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='api.productasset')),
                ('product', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='api.product')),
            ],
            options={
                'db_table': 'product_asset_links',
                'unique_together': {('product', 'asset')},
            },
        ),
    ]
