# Generated by Django 5.2.10 on 2026-02-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_productasset_productassetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='product price in pound, e.g. 199.99', max_digits=10),
        ),
    ]
