# Generated by Django 5.2.10 on 2026-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productasset_price_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productasset',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='flex',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productasset',
            name='topsheet_finish',
        ),
        migrations.AddField(
            model_name='product',
            name='p_desc',
            field=models.TextField(blank=True, help_text='产品描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_finish',
            field=models.CharField(blank=True, help_text='板面工艺，例如 matte / gloss', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='p_flex',
            field=models.CharField(blank=True, help_text='软硬度，例如 soft / regular / stiff', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='p_size',
            field=models.CharField(default='0', help_text='例如 140,160,180；无尺寸用 0', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='p_textures',
            field=models.JSONField(blank=True, default=dict, help_text='产品纹理JSON'),
        ),
    ]
