# Generated by Django 4.1.1 on 2026-02-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='user ID')),
                ('order_number', models.CharField(editable=False, help_text='12-digit unique order number', max_length=12, unique=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Completed', 'Completed')], default='Pending', help_text='order status: Pending/Confirmed/Shipped/Completed', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='total price in pounds, e.g. 199.99', max_digits=10)),
                ('address', models.TextField(blank=True, help_text='shipping address')),
                ('email', models.EmailField(blank=True, help_text='contact email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='unit price in pounds, e.g. 199.99', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, help_text='related customisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='m_products.customisation')),
                ('order', models.ForeignKey(help_text='related order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='m_shops.order')),
                ('product', models.ForeignKey(blank=True, help_text='related product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='m_products.product')),
            ],
            options={
                'db_table': 'm_order_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(help_text='user ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='单价，例如 199.99', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(help_text='用户选择的定制配置', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='m_products.customisation')),
            ],
            options={
                'db_table': 'm_cart',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'design')},
            },
        ),
    ]
