# Generated by Django 4.1.1 on 2026-02-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_users', '0001_initial'),
        ('m_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_users.userprofile')),
            ],
            options={
                'db_table': 'm_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
