# Generated by Django 5.2.11 on 2026-03-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'single'), (2, 'bundle')], default=1)),
                ('status', models.BooleanField(default=True, help_text='is product active?')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='product price in pound, e.g. 199.99', max_digits=10)),
                ('p_desc', models.TextField(blank=True, help_text='product description')),
                ('p_size', models.CharField(default='0', help_text='e.g. 140,160,180; no size use 0', max_length=100)),
                ('p_finish', models.CharField(blank=True, help_text='board finish, e.g. matte / glossy', max_length=50)),
                ('p_flex', models.CharField(blank=True, help_text='flexibility, e.g. soft / regular / stiff', max_length=50)),
                ('p_textures', models.JSONField(blank=True, default=list, help_text='product textures JSON')),
                ('is_double_sided', models.BooleanField(default=False, help_text='is double sided texture: False means single sided, True means both sides use the same image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_products',
            },
        ),
        migrations.CreateModel(
            name='ProductAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('texture_urls', models.JSONField(default=dict, help_text='例如 {"SB-001": ["front.png", "back.png"]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'm_product_assets',
            },
        ),
        migrations.CreateModel(
            name='Customisation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_size', models.CharField(blank=True, help_text='user selected size, e.g. 160', max_length=50)),
                ('p_finish', models.CharField(blank=True, help_text='user selected board finish, e.g. glossy', max_length=50)),
                ('p_flex', models.CharField(blank=True, help_text='user selected flexibility, e.g. soft', max_length=50)),
                ('p_textures', models.JSONField(blank=True, default=list, help_text='user selected textures, possibly multiple, stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='m_users.userprofile')),
                ('product', models.ForeignKey(help_text='user customised product', on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='m_products.product')),
            ],
            options={
                'db_table': 'm_customisations',
            },
        ),
        migrations.CreateModel(
            name='ProductAssetLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='m_products.productasset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='m_products.product')),
            ],
            options={
                'db_table': 'm_product_asset_links',
                'unique_together': {('product', 'asset')},
            },
        ),
    ]
